spring:
  cloud:
    gateway:
      routes:
        - id: before_route
          uri: http://localhost:8081/
          predicates:
            - Path=/echo/{segment}
            - After=2021-01-20T17:42:47.789-07:00[America/Denver]
          filters:
            - AddResponseHeader=X-Response-Red, Blue
