spring:
  profiles:
    active: dev
server:
  servlet:
    context-path: /mic
pxq:
  ignore-uri:
       - /auth/**
       - /login
       - /webjars/**
       - /swagger-resources/**
       - /doc.html
       - /v2/api-docs
       - /error/**
       - /favicon.ico
       - /images/**
       - /css/**
       - /js/*
  jwt:
    access-token-expires: 1H
    refresh-token-expires: 100H
